AllCops:
  TargetRubyVersion: 2.5
  NewCops: enable

Layout/LineLength:
  Max: 80

# double size metrics
Metrics/AbcSize:
  Max: 30
Metrics/BlockLength:
  Max: 50
Metrics/BlockNesting:
  Max: 6
Metrics/ClassLength:
  Max: 200
Metrics/CyclomaticComplexity:
  Max: 12
Metrics/MethodLength:
  Max: 20
Metrics/ModuleLength:
  Max: 200
Metrics/ParameterLists:
  Max: 10
Metrics/PerceivedComplexity:
  Max: 14

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation
Layout/EndOfLine:
  EnforcedStyle: lf
Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineMethodCallBraceLayout:
  EnforcedStyle: same_line
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/AsciiComments:
  Enabled: false
Style/BlockDelimiters:
  EnforcedStyle: line_count_based
  AllowBracesOnProceduralOneLiners: true
  BracesRequiredMethods: ['let']
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FormatString:
  EnforcedStyle: percent
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
Style/MultilineBlockChain:
  Enabled: false
Style/NumericLiterals:
  MinDigits: 7
Style/OneLineConditional:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/RescueStandardError:
  EnforcedStyle: implicit
Style/SpecialGlobalVars:
  EnforcedStyle: use_perl_names
Style/SymbolArray:
  MinSize: 8
Style/WordArray:
  MinSize: 8

# applications

Bundler/OrderedGems:
  Enabled: false
